{% set name = "pymem3dg" %}
{% set version = "0.0.6" %}
{% set sha256 = "4ba94b213d37a87d28da51cf9321e0c04208f4a33fcd2a5fdff069108a2ddcca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or py<35]
  script:
    - CXXFLAGS="${CXXFLAGS} -DTARGET_OS_OSX=1"  # [osx]
    - env
    - "CMAKE_GENERATOR=Ninja {{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - python    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11  # [build_platform != target_platform]
    - eigen 
  host:
    - python
    - pip
    - scikit-build-core
    - netcdf-cxx4
    - setuptools_scm
  run:
    - python
    - netcdf-cxx4
    - numpy
    - scipy
    - matplotlib-base
    - importlib_resources  # [py<39]
    - netCDF4
    - polyscope
    - seaborn
    - xarray

test:
  imports:
    - pymem3dg

about:
  home: https://github.com/RangamaniLabUCSD/Mem3DG
  license: MPL-2.0
  license_family: MOZILLA
  license_file: 
    - LICENSE
    - libraries/pcg/LICENSE-MIT.txt
    - libraries/geometry-central/LICENSE
    - libraries/libigl/LICENSE.GPL
    - libraries/libigl/LICENSE.MPL2

  summary: 'Membrane Dynamics in 3D using Discrete Differential Geometry'

  description: |
    PyMem3DG performs membrane simulations.
  doc_url: https://rangamanilabucsd.github.io/Mem3DG/
  dev_url: https://github.com/RangamaniLabUCSD/Mem3DG

extra:
  recipe-maintainers:
    - CunchengZhu
    - ctlee
    - cuzhucuncheng
