{% set name = "pymem3dg" %}
{% set version = "0.0.6rc1" %}
{% set sha256 = "c658dbaf4ab9238462737ff6046817a85fb35e94565dff0cc8608000f2b7e5d1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or py<35]
  script:
    - CXXFLAGS="${CXXFLAGS} -DTARGET_OS_OSX=1"  # [osx]
    - env
    - "CMAKE_GENERATOR=Ninja {{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pybind11
    - eigen
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
  host:
    - python
    - pip
    - scikit-build
    - netcdf-cxx4
    - xorg-libxfixes  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxi  # [linux]
    - importlib_resources  # [py<39]
  run:
    - python
    - netcdf-cxx4
    - xorg-libx11  # [linux]
    - importlib_resources  # [py<39]

test:
  imports:
    - pymem3dg

about:
  home: https://github.com/RangamaniLabUCSD/Mem3DG
  license: MPL-2.0
  license_family: MOZILLA
  license_file: 
    - LICENSE
    - libraries/pcg/LICENSE-MIT.txt
    - libraries/geometry-central/LICENSE
    - libraries/polyscope/LICENSE

  summary: 'Membrane Dynamics in 3D using Discrete Differential Geometry'

  description: |
    PyMem3DG performs membrane simulations.
  doc_url: https://rangamanilabucsd.github.io/Mem3DG/
  dev_url: https://github.com/RangamaniLabUCSD/Mem3DG

extra:
  recipe-maintainers:
    - ctlee
    - cuzhucuncheng
